name: benstr
favicon: null
layout_spectrum: 0.337093103909865
typography_spectrum: 0.6675587159115821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3587137907743454
  lightness: 0.7772538205608726
  saturation: 0.8294112640433013
  rhythmicContrast: 0.9660351264756173
purpose: []
